import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center mt-16">
        <div className="py-1.5 px-4 tracking-wider text-4xl text-center">
          FIND MY PROFESSORS
        </div>
        <div className="flex">
          <select className="border px-2 py-2 mt-5 outline-none text-sm">
            <option value="UCF">UCF</option>
            <option value="UF">UCF</option>
          </select>
          <input
            className="border px-3.5 py-2 mt-5 outline-none text-sm"
            placeholder="Course name"
            type="text"
          />
        </div>
      </div>
    </div>
  );
};

export default Home;
